yarnPath: .yarn/releases/yarn-4.9.1.cjs
nodeLinker: node-modules

# Enable dependency hoisting for shared packages
nmHoistingLimits: workspaces

# Configure peer dependency resolution
pnpFallbackMode: dependencies-only

# Auto-install peer dependencies when possible
enableGlobalCache: false

